package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

func handleError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

type ComponentGroup struct {
	ID                 string `json:"id"`
	PageID             string `json:"page_id"`
	GroupID            string `json:"group_id"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
	Group              bool   `json:"group"`
	Name               string `json:"name"`
	Description        string `json:"description"`
	Position           int    `json:"position"`
	Status             string `json:"status"`
	Showcase           bool   `json:"showcase"`
	OnlyShowIfDegraded bool   `json:"only_show_if_degraded"`
	AutomationEmail    string `json:"automation_email"`
	StartDate          string `json:"start_date"`
}

type ComponentGroups []ComponentGroup

// Component was auto-generated by rea
type Component struct {
	AutomationEmail    string  `json:"automation_email"`
	CreatedAt          string  `json:"created_at"`
	Description        string  `json:"description"`
	Group              bool    `json:"group"`
	GroupId            string  `json:"group_id"`
	Id                 string  `json:"id"`
	Name               string  `json:"name"`
	OnlyShowIfDegraded bool    `json:"only_show_if_degraded"`
	PageId             string  `json:"page_id"`
	Position           float64 `json:"position"`
	Showcase           bool    `json:"showcase"`
	StartDate          string  `json:"start_date"`
	Status             string  `json:"status"`
	UpdatedAt          string  `json:"updated_at"`
}

func (c Component) Print() string {
	return fmt.Sprintf("\"%s\",\"%s\",%s\n", c.Name, c.GroupId, c.Status)
}

// Components is multiple Component
type Components []Component

type ComponentCollector struct {
	Status      *prometheus.Desc
	Operational *prometheus.Desc
}

func NewComponentCollector() *ComponentCollector {
	return &ComponentCollector{
		Status:      prometheus.NewDesc(prometheus.BuildFQName("component", "", "status"), "Status", []string{"name", "group", "id", "group_id", "status"}, nil),
		Operational: prometheus.NewDesc(prometheus.BuildFQName("component", "", "operational"), "Status", []string{"name", "group", "id", "group_id"}, nil),
	}
}

func (cc *ComponentCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- cc.Status
}

func (cc *ComponentCollector) Collect(ch chan<- prometheus.Metric) {
	groups, err := getGroups()
	handleError(err)

	components, err := getComponents()
	handleError(err)

	for _, c := range components {
		group := ""
		if c.GroupId != "" {
			group = groups[c.GroupId]
		}

		ch <- prometheus.MustNewConstMetric(cc.Status, prometheus.GaugeValue, 1, c.Name, group, c.Id, c.GroupId, c.Status)

		if c.Status == "operational" {
			ch <- prometheus.MustNewConstMetric(cc.Operational, prometheus.GaugeValue, 1, c.Name, group, c.Id, c.GroupId)
		} else {
			ch <- prometheus.MustNewConstMetric(cc.Operational, prometheus.GaugeValue, 0, c.Name, group, c.Id, c.GroupId)
		}
	}
}

func statusPageAPI(url string) ([]byte, error) {
	token := os.Getenv("TOKEN")

	client := &http.Client{}

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Authorization", fmt.Sprintf("OAuth %s", token))

	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}

	return io.ReadAll(resp.Body)
}

func getGroups() (map[string]string, error) {
	pageId := os.Getenv("PAGE_ID")
	url := fmt.Sprintf("https://api.statuspage.io/v1/pages/%s/components?page=1&per_page=500", pageId)

	body, err := statusPageAPI(url)
	if err != nil {
		return nil, err
	}

	var compGroups ComponentGroups
	err = json.Unmarshal(body, &compGroups)
	if err != nil {
		return nil, err
	}

	groups := make(map[string]string)
	for _, cg := range compGroups {
		if cg.GroupID == "" {
			continue
		}
		groups[cg.GroupID] = cg.Name
	}

	return groups, nil
}

func main() {
	reg := prometheus.NewRegistry()
	reg.MustRegister(NewComponentCollector())

	fmt.Println("Now serving metrics at http://localhost:9101/metrics")
	http.Handle("/metrics", promhttp.HandlerFor(reg, promhttp.HandlerOpts{}))
	log.Fatal(http.ListenAndServe(":9101", nil))
}

func getComponents() (Components, error) {
	pageId := os.Getenv("PAGE_ID")

	// TODO: Figure out values for pagination
	url := fmt.Sprintf("https://api.statuspage.io/v1/pages/%s/components?page=1&per_page=500", pageId)

	body, err := statusPageAPI(url)
	if err != nil {
		return nil, err
	}

	var comps Components
	err = json.Unmarshal(body, &comps)
	if err != nil {
		fmt.Println(string(body))
		handleError(err)
	}

	return comps, nil
}
