package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

func handleError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

// Component was auto-generated by rea
type Component struct {
	AutomationEmail    string  `json:"automation_email"`
	CreatedAt          string  `json:"created_at"`
	Description        string  `json:"description"`
	Group              bool    `json:"group"`
	GroupId            string  `json:"group_id"`
	Id                 string  `json:"id"`
	Name               string  `json:"name"`
	OnlyShowIfDegraded bool    `json:"only_show_if_degraded"`
	PageId             string  `json:"page_id"`
	Position           float64 `json:"position"`
	Showcase           bool    `json:"showcase"`
	StartDate          string  `json:"start_date"`
	Status             string  `json:"status"`
	UpdatedAt          string  `json:"updated_at"`
}

func (c Component) Print() string {
	return fmt.Sprintf("\"%s\",\"%s\",%s\n", c.Name, c.GroupId, c.Status)
}

// Components is multiple Component
type Components []Component

type ComponentCollector struct {
	Status      *prometheus.Desc
	Operational *prometheus.Desc
}

func NewComponentCollector() *ComponentCollector {
	return &ComponentCollector{
		Status:      prometheus.NewDesc(prometheus.BuildFQName("component", "", "status"), "Status", []string{"name", "group_id", "status"}, nil),
		Operational: prometheus.NewDesc(prometheus.BuildFQName("component", "", "operational"), "Status", []string{"name", "group_id"}, nil),
	}
}

func (cc *ComponentCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- cc.Status
}

func (cc *ComponentCollector) Collect(ch chan<- prometheus.Metric) {
	for _, c := range getComponents() {
		ch <- prometheus.MustNewConstMetric(cc.Status, prometheus.GaugeValue, 1, c.Name, c.GroupId, c.Status)
		if c.Status == "operational" {
			ch <- prometheus.MustNewConstMetric(cc.Operational, prometheus.GaugeValue, 1, c.Name, c.GroupId)
		} else {
			ch <- prometheus.MustNewConstMetric(cc.Operational, prometheus.GaugeValue, 0, c.Name, c.GroupId)
		}
	}
}

func main() {
	reg := prometheus.NewRegistry()
	reg.MustRegister(NewComponentCollector())

	fmt.Println("Now serving metrics at http://localhost:9101/metrics")
	http.Handle("/metrics", promhttp.HandlerFor(reg, promhttp.HandlerOpts{}))
	log.Fatal(http.ListenAndServe(":9101", nil))
}

func getComponents() Components {
	pageId := os.Getenv("PAGE_ID")
	token := os.Getenv("TOKEN")

	// TODO: Figure out values for pagination
	url := fmt.Sprintf("https://api.statuspage.io/v1/pages/%s/components?page=1&per_page=500", pageId)

	client := &http.Client{}

	req, err := http.NewRequest("GET", url, nil)
	handleError(err)

	req.Header.Add("Authorization", fmt.Sprintf("OAuth %s", token))

	resp, err := client.Do(req)
	handleError(err)

	body, err := io.ReadAll(resp.Body)
	handleError(err)

	var comps Components
	handleError(json.Unmarshal(body, &comps))

	return comps
}
