apiVersion: v1
kind: Template
metadata:
  name: statuspage-exporter
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${NAME}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "multiple replicas is multiple cost"
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        serviceAccountName: ${NAME}
        containers:
        - name: statuspage-exporter
          image: ${IMAGE}:${IMAGE_TAG}
          ports:
          - containerPort: 9115
            name: http
            protocol: TCP
          env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: ${TOKEN_SECRET_NAME}
                key: ${TOKEN_SECRET_KEY}
          resources:
            limits:
              cpu: ${CPU_LIMITS}
              memory: ${MEMORY_LIMITS}
            requests:
              cpu: ${CPU_REQUESTS}
              memory: ${MEMORY_REQUESTS}
          # TODO:
          # readinessProbe:
          #   failureThreshold: 3
          #   periodSeconds: 10
          #   successThreshold: 1
          #   httpGet:
          #     path: /
          #     port: http
          #     scheme: HTTP
          #   timeoutSeconds: 1
          #   initialDelaySeconds: 10
          # livenessProbe:
          #   failureThreshold: 3
          #   periodSeconds: 10
          #   successThreshold: 1
          #   httpGet:
          #     path: /
          #     port: http
          #     scheme: HTTP
          #   timeoutSeconds: 1
          #   initialDelaySeconds: 10
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    selector:
      app: ${NAME}
    ports:
    - name: http
      protocol: TCP
      port: 9115
      targetPort: 9115
    type: ClusterIP
parameters:
- name: NAME
  value: statuspage-exporter
- name: IMAGE
  value: quay.io/app-sre/statuspage-exporter
- name: IMAGE_TAG
  value: latest
- name: REPLICAS
  value: "1"
- name: TOKEN_SECRET_NAME
  value: statuspage-exporter
- name: TOKEN_SECRET_KEY
  value: TOKEN
- name: CPU_LIMITS
  value: 200m
- name: CPU_REQUESTS
  value: 200m
- name: MEMORY_LIMITS
  value: 150Mi
- name: MEMORY_REQUESTS
  value: 150Mi
